version: '3.7'

services: 

  frontend:
    container_name: docker-react-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true
      