FROM node:14.4.0 AS builder

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN npm install react-scripts@3.4.1 -g

COPY . ./
RUN npm run build

FROM nginx:1.17-alpine
RUN apk --no-cache add curl
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst-`uname -s`-`uname -m` -o envsubst && chmod +x envsubst && \ mv envsubst /usr/local/bin

COPY ./nginx.config /etc/nginx/nginx.template
